### PR TITLE
Feature retraction

### PR DESCRIPTION
**Pull request by gnott**
Fixes https://github.com/elifesciences/elife-pubmed-feed/issues/72.

### CODE REVIEW

**Comment by gnott** [comment]
To deploy, the ``elife-bot`` ``requirements.txt`` commit for the pubmed library will need to be updated, plus depends on https://github.com/elifesciences/elife-bot-formula/pull/18.

**Comment by giorgiosironi** [comment]
Interesting, we have never published a `retraction` before? @sianroderick 
If I can get a hold of a sample .zip package for the bot I can add it to the end2end tests?

**Comment by sianroderick** [comment]
@giorgiosironi Melissa pushed https://continuumtest--journal.elifesciences.org/articles/34464 through the test site, so the package should be available in the associated bucket.

**Comment by gnott** [comment]
The sample I looked at, there is a planned change to the tagging. Instead of

```
<related-article related-article-type="corrected-article" ...
```
it will have
```
<related-article related-article-type="retracted-article" ...
```

If you want to change the XML in a package for end2end testing to reflect the above, and then you could test its PubMed result to specifically look at the ``<PublicationType>`` and ``<Object>`` tagging in the pubmed batch file, if you want to go into that great detail.

**Comment by gnott** [comment]
Should we hold off deploying the retraction support here @giorgiosironi until you've confirmed an end2end test is created?

**Comment by giorgiosironi** [comment]
The dependency is the other way around: to run successfully, an end2end tests needs the feature to already be there.

**Review by giorgiosironi — APPROVED** [review]

**Comment by gnott** [comment]
Thanks @giorgiosironi, merging and to the next step!

**Pull request merged**
